# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=5000

EXPOSE ${PORT}

CMD python app.py